- name: "Install prerequesite"
  apt:
    name: "{{item}}"
    state: present
    update_cache: true
  with_items:
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "gnupg2"
    - "software-properties-common"
  become: true

- name: "Add GPG key"
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
  become: true

- name: "Add APT repository"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{lsb_release}} stable"
    state: present
  become: true

- name: "Install Docker CE"
  apt:
    name: "docker-ce"
    state: present
    update_cache: true
  become: true

- name: "Add user in docker group"
  user:
    name: "{{ansible_user}}"
    groups: docker
    append: yes
  become: true

- name: "Install docker-compose"
  get_url:
    url: https://github.com/docker/compose/releases/download/{{docker_compose_version}}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
  become: true
