- name: "Install Git"
  apt:
    name: "git"
    state: present
    update_cache: true
  become: true
  tags:
    - ubuntu

- name: "set Git Symbolic link"
  file:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    state: link
  with_items:
    - { src: '${HOME}/workspace/github/jgsqware/env/git/.gitconfig', dest: '~/.gitconfig' }
    - { src: '${HOME}/workspace/github/jgsqware/env/git/.gitignore_global', dest: '~/.gitignore_global' }
  tags:
    - always
    