---
- name: Download the Go tarball
  get_url:
    url: "{{ go_download_location }}"
    dest: /usr/local/src/{{ go_tarball }}
    checksum: "{{ go_tarball_checksum }}"
  become: true
  tags:
    - always

- name: Register the current Go version (if any)
  command: /usr/local/go/bin/go version
  ignore_errors: yes
  register: go_version
  changed_when: false
  tags:
    - always
    
- name: Remove old installation of Go
  file:
    path: /usr/local/go
    state: absent
  when: go_version|failed or go_version.stdout != go_version_target
  tags:
    - always
    
- name: Extract the Go tarball if Go is not yet installed or not the desired version
  unarchive:
    src: /usr/local/src/{{ go_tarball }}
    dest: /usr/local
    copy: no
  when: go_version|failed or go_version.stdout != go_version_target
  become: true
  tags:
    - always
    