- name: "Install tools"
  apt:
    name: "{{item}}"
    state: present
    update_cache: true
  with_items:
    - "jq"
    - "source-highlight"
    - "curl"
    - "fonts-firacode"
  become: true

# - include: "git.yml"
# - include: "go.yml"
# - include: "vscode.yml"
# - include: "spotify.yml"
# - include: "opera.yml"
# - include: "vim.yml"
# - include: "slack.yml"
# - include: "rescuetime.yml"
# - include: "docker.yml"
# - include: "virtualbox.yml"
# - include: "minikube.yml"
- include: "enpass.yml"
