- name: "Install tools"
  apt:
    name: "{{item}}"
    state: present
    update_cache: true
  with_items:
    - "jq"
    - "source-highlight"
    - "curl"
    - "fonts-firacode"
    - "mkchromecast"
  become: true
  tags:
    - ubuntu

- include: "cower.yml"
  tags:
    - artengos


- include: "git.yml"
- include: "go.yml"
- include: "vscode.yml"
- include: "spotify.yml"
- include: "opera.yml"
- include: "vim.yml"
- include: "slack.yml"
- include: "rescuetime.yml"
- include: "docker.yml"
- include: "virtualbox.yml"
- include: "minikube.yml"
- include: "enpass.yml"
- include: "dropbox.yml"
- include: "keybase.yml"
- include: "laverna.yml"
- include: "mkchromecast.yml"
