- name: Add the opera APT key
  apt_key: 
    url: http://deb.opera.com/archive.key 
    state: present
  become: true
  tags:
    - ubuntu

- name: Add opera repo
  apt_repository: 
    repo: "deb http://deb.opera.com/opera/ stable non-free" 
    state: present
  become: true
  tags:
    - ubuntu

- name: Install opera
  apt: 
    name: opera-stable
    state: latest
  become: true
  register: opera_state
  tags:
    - ubuntu

- name: Install opera
  pacman:
    name: opera
    state: present
  when: opera_state.changed
  become: true
  tags:
    - artengos

- name: "Close running opera"
  shell: "killall opera || true"
  when: opera_state.changed
  tags:
    - ubuntu     
    - artengos
  
- name: "Install Enpass extension (Close opera when done)"
  command: "opera https://addons.opera.com/en/extensions/details/enpass-password-manager-extension-for-opera/"
  when: opera_state.changed
  tags:
    - ubuntu
    - artengos

- name: "Install gnome-shell-integration extension (Close opera when done)"
  command: "opera   https://addons.opera.com/en/extensions/details/gnome-shell-integration/"
  when: opera_state.changed
  tags:
    - ubuntu
    - artengos
