- name: "Install vim"
  apt:
    name: "vim"
    state: present
    update_cache: true
  become: true
  tags:
    - ubuntu

- name: "Install vim"
  pacman:
    name: vim
    state: latest
    update_cache: true
  become: true
  tags:
    - artengos

- name: "set Vim Symbolic link"
  file:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    state: link
  with_items:
    - { src: '${HOME}/workspace/github/jgsqware/env/vim/.vim', dest: '${HOME}/.vim' }
    - { src: '${HOME}/workspace/github/jgsqware/env/vim/.vimrc', dest: '~/.vimrc' }
  tags:
    - always
    
- name: "Install Plugins"
  command: "vim +PlugInstall +qall"
  async: 1000
  poll: 10
  tags:
    - always
      