- name: Configure the Oracle APT key
  apt_key: 
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present
  become: true

- name: Configure the VirtualBox APT repositories
  apt_repository: 
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ lsb_release }} contrib"
    state: present
  become: true


- name: Install VirtualBox
  apt: 
    pkg: virtualbox-{{ virtualbox_version }} 
    state: present
  become: true
  