- name: "Install VSCode"
  apt:
    deb: https://go.microsoft.com/fwlink/?LinkID=760868
  become: true
  tags:
    - ubuntu


- name: "Install VSCode"
  aur:
    name: visual-studio-code
    user: "{{ansible_user}}"
  tags:
    - artengos

# - name: "Install Sync extension"
#   command: "code --install-extension Shan.code-settings-sync"
  # tags:
  #   - always