- name: "Install VSCode"
  apt:
    deb: https://go.microsoft.com/fwlink/?LinkID=760868
  become: true

# - name: "Install Sync extension"
#   command: "code --install-extension Shan.code-settings-sync"