go_tarball: "go1.8.3.linux-amd64.tar.gz"
go_tarball_checksum: "sha256:1862f4c3d3907e59b04a757cfda0ea7aa9ef39274af99a784f5be843c80c6772"
go_version_target: "go version go1.8.3 linux/amd64"
go_download_location: "https://storage.googleapis.com/golang/{{ go_tarball }}"

virtualbox_version: 5.1

docker_compose_version: 1.15.0

spotify_scaling_factor: 2.0
slack_version: 2.7.1
laverna_version: 0.7.3