- name: "Install tools"
  apt:
    name: "{{item}}"
    state: present
    update_cache: true
  with_items:
    - "jq"
    - "source-highlight"
    - "curl"
    - "fonts-firacode"
  become: true

- name: "Download Konsole Color profile"
  get_url:
    url: "https://raw.githubusercontent.com/cskeeters/base16-konsole/master/colorscheme/base16-chalk.colorscheme"
    dest: /usr/share/konsole/base16-chalk.colorscheme
    mode: 0755
  become: true

- name: "Change Konsole theme"
  command: "konsoleprofile colors=base16-chalk"

- name: "Install VSCode"
  apt:
    deb: https://go.microsoft.com/fwlink/?LinkID=760868
  become: true

- name: Add apt keys
  apt_key: 
    keyserver: keyserver.ubuntu.com 
    id: "{{ item }}"
    state: present
  with_items:
    - BBEBDCB318AD50EC6865090613B00F1FD2C19886
    - 0DF731E45CE24F27EEEB1450EFDC8610341D9410
  become: true

- name: Add repository
  apt_repository: 
    repo: 'deb http://repository.spotify.com stable non-free'
  become: true

- name: Install spotify
  apt: 
    name: spotify-client 
    update_cache: yes 
    state: latest
  become: true
  
- name: Add opera repo
  apt_repository: repo="deb http://deb.opera.com/opera/ stable non-free" state=present

- name: Add the opera APT key
  apt_key: url=http://deb.opera.com/archive.key state=present

- name: Install opera
  apt: name={{item}} state=latest
  with_items:
  - opera