---
- hosts: all
  pre_tasks:
    - name: Install mandatory tools
      pacman:
        name: "{{item}}"
        state: latest
        update_cache: yes
      with_items:
        - lsb-release
        - dmidecode
      become: true
      tags:
        - artengos

    - name: Get lsb release
      command: lsb_release -cs
      register: cmd_lsb_release
      tags:
        - ubuntu
        - artengos

    - name: get product name
      command: "dmidecode -s system-product-name"
      register: cmd_product_name
      become: true
      tags:
        - ubuntu
        - artengos

    - name: Save facts
      set_fact:
        lsb_release: "{{cmd_lsb_release.stdout}}"
        product_name: "{{ cmd_product_name.stdout }}"
      tags:
        - ubuntu
        - artengos

  roles:
    - role: oh-my-zsh
    - role: tools
    - role: kde
    - role: laptop-setup
  post_tasks:
    - debug: 
        msg: 
          - "1. Change the KDE look and feel to Arc Dark"
          - "   System Settings -> Workspace Theme -> Look and Feel -> Arc Dark"
          - "   Check 'Use Desktop Layout from theme'"
          - " "
          - "2. Disable <Alt+LeftMouse>"
          - "   System Settings -> Window Management -> Window Behaviour -> Window Actions - Inner Window, Titlebar & Frame -> Left button -> Nothing"
          - "2. Sync VSCode"
          - "   Shift + Alt + D -> Enter GIST (from Enpass)"
          - " "
          - "3. Logout - Login for"
          - "   - theme"
          - "   - docker"
      tags:
        - always