---
- hosts: all
  pre_tasks:
    - name: Install lsb_release
        pacman:
          name: lsb_release
          state: latest
          update_cache: yes
      tags:
        - artengos
    - name: Get lsb release
      command: lsb_release -cs
      register: cmd_lsb_release
      tags:
        - artengos
        - ubuntu
    - name: get product name
      command: "dmidecode -s system-product-name"
      register: cmd_product_name
      become: true
      tags:
        - artengos
        - ubuntu

    - name: Save facts
      set_fact:
        lsb_release: "{{cmd_lsb_release.stdout}}"
        product_name: "{{ cmd_product_name.stdout }}"
      tags:
        - artengos
        - ubuntu

  roles:
    - role: tools
    # - role: oh-my-zsh
    # - role: kde
    # - role: laptop-setup
  post_tasks:
    - debug: 
        msg: 
          - "1. Change the KDE look and feel to Arc Dark"
          - "   System Settings -> Workspace Theme -> Look and Feel -> Arc Dark"
          - "   Check 'Use Desktop Layout from theme'"
          - " "
          - "2. Sync VSCode"
          - "   Shift + Alt + D -> Enter GIST (from Enpass)"
          - "3. Logout - Login for"
          - "   - theme"
          - "   - docker"