---
- hosts: all
  roles:
    - role: tools
    # - role: oh-my-zsh
    # - role: kde
    # - role: laptop-setup
  post_tasks:
    - debug: 
        msg: 
          - "1. Change the KDE look and feel to Arc Dark"
          - "   System Settings -> Workspace Theme -> Look and Feel -> Arc Dark"
          - "   Check 'Use Desktop Layout from theme'"